### ISSUE TITLE
Element list in control panel - color preview is not displaying corretly if selected option has more than one color

### ISSUE THREAD

**Issue by piotrpog** [percipioglobal/craft-colour-swatches#101]
By color preview i mean this small circle. Its style looks like this: `background-color:#1abc9c,#e74c3c` instead of displaying CSS gradient like it does in field widget.

**Comment by cookie10codes** [comment]
Hi @piotrpog,

Can you provide us which Color Swatch version is installed on your system en which Craft version you are on?

You can check that in Utilities > System Report

Thank you

**Comment by piotrpog** [comment]
Here is my system information;

PHP version | 8.1.2
MySQL 5.5.5
Craft Pro 4.2.5.1
Colour Swatches | 4.2.0.1

**Comment by cookie10codes** [comment]
thanks @piotrpog,

I'll add it to our planning to get this sorted

**Comment by cookie10codes** [comment]
@piotrpog looking in to this issue but I don't see anything wrong. This is how it should display as below. If it looks different than below, please re-open the issue and attach your screenshot to it

<img width="213" alt="Screenshot 2022-09-30 at 10 30 30" src="https://user-images.githubusercontent.com/20947573/193227718-15b82199-10a0-4e1b-a78b-73d0420909dc.png">

**Comment by piotrpog** [comment]
@cookie10codes 
hi, sorry for the late reply. Your screen shows element details (color selection widget). And my issue is about element index list. Here is what it looks like - first entry has color with multiple hex codes selected, second entry has color with single hex code selected.

![image](https://user-images.githubusercontent.com/42622545/195949042-56dc155a-bb19-42bd-99a2-274a9e73e41e.png)

By the way, would be cool if this circle had `title` attribute with name of color, so we can hover circle and see see it.

**Comment by cookie10codes** [comment]
@piotrpog sorry for the late reply on this. I've fixed the table attribute and release 4.2.1, can you update the package to see if it's fixed on your end as well?

If something isn't working, re-open this issue please. Thank you!

Have a nice day
