### ISSUE TITLE
Array to String conversion error

### ISSUE THREAD

**Issue by CreateSean** [percipioglobal/craft-colour-swatches#103]
I'm trying to get classes to output in the template but the only thing that will successfully output is the label name.

color-swatches.php
```php
    'palettes' => [
      'Hero' => [  // custom label
        [
            'label'   => 'White',
            'default' => true,
            'color'   =>  [
                [
                    'color'             => '#ffffff', // the colour shown in the fieldtype (required)
                    'background'        => 'bg-white',
                    'backgroundHover'   => 'bg-white',
                    'text'              => 'text-white',
                    'textHover'         => 'text-gray-100'
                ]
            ]
        ],
        [
          'label'   => 'Gray',
          'default' => false,
          'color'   =>  [
              [
                  'color'             => '#cccccc',               // the colour shown in the fieldtype (required)
                  'background'        => 'bg-gray-500',
                  'backgroundHover'   => 'bg-gray-500',
                  'text'              => 'bg-gray-500',
                  'textHover'         => 'bg-gray-500'
              ]
          ]
      ],
      ],
    ]
```

The color field is in a matrix block and I've tried the following

`{{ block.backgroundColor }}` outputs label

`{{ block.backgroundColor.color }}` array to string conversion error

```twig
  {% for field in block.backgroundColor %}
    background: {{ field.text }} <br>
    text: {{ field.text }}
  {% endfor %}
```

error: `Impossible to access an attribute ("text") on a string variable ("Gray").`

Please advise

**Comment by amphibian** [comment]
Not sure if this is a bug or just a case of poor documentation, but this syntax works for me after encountering this same issue. (Note that you need to loop through the **color** array specifically):

```
{% for color in fieldName.color %}
    background: {{ color.color }}
    text: {{ color.customAttribute }}
{% endfor %}
```

**Comment by CreateSean** [comment]
@amphibian Thank you. that worked

**Comment by cookie10codes** [comment]
hi @CreateSean,

Can you show me on how you build your Matrix? If I dump out a colour block I've made inside of a matrix, I do get the info needed. But you need to make sure to loop through color

Looping through the colours:
```
{%- for block in entry.matrix -%}
    Dump:
    <pre>
        {{ dump(block.colour.color[0]) }}
    </pre>
    {% for color in block.colour.color %}
        color: {{ color.color }}<br/>
        backgroundHover: {{ color.backgroundHover }}<br/>
    {% endfor %}
{%- endfor -%}
```

If you want to know if a colour is selected you can do:
```
{{ block.colour.color[0].color ?? null }}
```

This gives me this output:
```
Dump:
array(5) {
  ["color"]=>
  string(7) "#ffffff"
  ["background"]=>
  string(8) "bg-white"
  ["backgroundHover"]=>
  string(8) "bg-white"
  ["text"]=>
  string(10) "text-white"
  ["textHover"]=>
  string(13) "text-gray-100"
}

            
color: #ffffff
backgroundHover: bg-white
```


My matrix field looks like this:
<img width="1326" alt="Screenshot 2022-12-21 at 12 09 17" src="https://user-images.githubusercontent.com/20947573/208891529-96c0f95e-1641-4bb8-a6a8-f764e33c63ef.png">

**Comment by chadcrowell** [comment]
I just ran into this and found that if I change the config file like this:

```
            [
                'label'   => 'Black',
                'default' => false,
                'color'   =>  [
                                      'color' => '#000000',
                                      'background' => 'bg-black'
                                     ]
            ],
```

(single array brackets instead of double, on the 'color' attribute)

That I can use:

`{% set bgColor = textColor.color.background %}`

And it works.
