### ISSUE TITLE
Default swatch value returns as null

### ISSUE THREAD

**Issue by gateszies** [percipioglobal/craft-colour-swatches#109]
We're experiencing a bug with this plugin where the selected default value is not actually defining anything by default. 

Our Colour Swatch field has the default swatch selected as indicated with the checkmark.
<img width="668" alt="Screen Shot 2023-05-23 at 5 08 51 PM" src="https://github.com/percipioglobal/craft-colour-swatches/assets/66807975/4e20f8cc-8bc5-4afd-a529-8d5119a01808">

The default swatch is also indicated by the highlighted option on the entry that uses the field.
<img width="247" alt="Screen Shot 2023-05-23 at 5 10 44 PM" src="https://github.com/percipioglobal/craft-colour-swatches/assets/66807975/47dcd942-5f26-4616-8413-3aad8d11f615">

When we load the page, however, we are getting an error that indicates the field value is null. This is confirmed by dumping the value of the field on a blank page which also returns null.
<img width="871" alt="Screen Shot 2023-05-23 at 5 11 57 PM" src="https://github.com/percipioglobal/craft-colour-swatches/assets/66807975/657e1f10-2891-4cce-9fe6-16c05bb8466b">

If you interact with the field and select a color, everything works as intended. But the field **must** be interacted with, making the default option not functional. The selected default swatch option should pass through the value of the swatch without the user needing to interact with the field and select a swatch.

We are currently running on **Craft 4.4.7.1** and **Colour Swatch 4.3.0**.

**Comment by cookie10codes** [comment]
@gateszies thank you for reporting this bug, sorry you've had to wait for answers. This will be fixed in the next release

**Comment by gateszies** [comment]
Thanks so much @cookie10codes!

**Comment by turnstylerj** [comment]
Any ETA on this fix getting in? This is still an issue on v4.3.0 and prevents Colour Swatches fields from being required and saved as-is in a field layout.

![2024-03-19 at 15 36 41](https://github.com/craftpulse/craft-colour-swatches/assets/42223501/c937e9c8-44fa-4ec7-b6c1-aba4bcd3f876)

**Comment by cookie10codes** [comment]
hi @turnstylerj , sorry to get back so late on this issue. We recently took over the plugins and we're planning some development work. We will take this issue prior on our task list

**Comment by cookie10codes** [comment]
sorry for the wait @gateszies and @turnstylerj, this has been fixed on C4

**Comment by turnstylerj** [comment]
Awesome, cheers!
