### ISSUE TITLE
Syntax error when switching from Dropdown field type

### ISSUE THREAD

**Issue by CharlieGentle** [percipioglobal/craft-colour-swatches#111]
Had an issue switching from a Dropdown field to a Colour Swatches field.

Error was with [line 57 of src/models/ColourSwatches.php](https://github.com/percipioglobal/craft-colour-swatches/blob/e42b9da2d407e38463b90413eef9c8047aa9ddab/src/models/ColourSwatches.php#L57) as the value was not a JSON string. I couldn't open an entry in the CP to resave the entry with the new value.

Changing `Json::decode($value)` to `Json::decodeIfJson($value)` allowed me to resave all affected entries.

**Comment by cookie10codes** [comment]
@CharlieGentle sorry for the wait, this is fixed in C4
