### ISSUE TITLE
[Docs] Incorrect plugin name used in installation step

### ISSUE THREAD

**Issue by chrismlusk** [percipioglobal/craft-colour-swatches#115]
Step 2 of installation says to run:

```
 composer require percipiolondon/craft-colour-swatches
```

But that throws an error that `percipiolondon/craft-colour-swatches` cannot be found.

On the Craft 4 Plugin Store, the documentation also mentions this, but the copy to clipboard utility in the right column has:

```
composer require craftpulse/craft-colour-swatches
```

I am able to install this successfully.

Has the namespace changed again?

**Comment by michtio** [comment]
Correct - This has changed. 

Thank you for pointing this out. All plugins will be update ready for Craft 5.  And documentation will be updated too
