### ISSUE TITLE
Craft 5 Support

### ISSUE THREAD

**Issue by stephenheron** [percipioglobal/craft-colour-swatches#116]
Hello,

Just wondering if this plugin is getting bumped to support Craft 5? 

I made a quick fork just to see if it works, I simply bumped up the min Craft version in the composer file and it worked. 

The only thing that was "broken" is the field was missing an icon and that was quick fix. (https://github.com/stephenheron/craft-colour-swatches/commit/04585bf78e4d9977bea18587b7a1cfcce45347cc)

Thanks,
Stephen

**Comment by russback** [comment]
Any update or schedule on this? Craft 5 is launching this month.

**Comment by michtio** [comment]
> Any update or schedule on this? Craft 5 is launching this month.

Craft 5 will be released Next Month (April) not this month. But all plugins will be ready when Craft 5 goes live.

**Comment by michtio** [comment]
So @stephenheron @russback - seems like Craft did launch in March. Missed the announcement completely from P&T ahead of time.

I can mention tho we moved up the process to update all our plugins next week. Stay tuned!

**Comment by ishetnogferre** [comment]
@cookie10codes I see [a Craft 5 release was pushed](https://github.com/craftpulse/craft-colour-swatches/releases/tag/5.0.0), but it isn't showing up in the Craft 5 store yet. Could this be due the outdated composer.lock maybe? Thanks!

**Comment by cookie10codes** [comment]
hi @ishetnogferre, thanks for mentioning, I'll have a look why it's not provided yet

You can already install the plugin with composer on your Craft 5 install
