### ISSUE TITLE
Undefined Array Key 0 Error in Craft 5.36 Colour Swatches 5.0.2

### ISSUE THREAD

**Issue by brianrivet-tilt** [percipioglobal/craft-colour-swatches#133]
I am now getting the Undefined Array Key 0 error when I try to save entries with the color swatch field in them. 

I made changes to the values in the field settings for the field and the error started after that.

The error only seems to happen with existing entries and not with new entries, but it is preventing any changes from being saved to the affected entries.

I'm running Craft 5.3.6 and Colour Swatches v5.0.2

**Comment by michtio** [comment]
@brianrivet-tilt I have tested this, but couldn't replicate.

If possible (and allowed) could you send over your composer.json and potential DB backup to development@pau.be and mention on which entry you encounter this?

Feel free to remove anything from the DB and create a simple reproducable example.

Thank you!

**Comment by brianrivet-tilt** [comment]
Thanks! I've sent a link to download the necessary files along with instructions for how to see the error. LEt me know if you need anything else from me.

**Comment by michtio** [comment]
@brianrivet-tilt thank you! Email received.
