### ISSUE TITLE
Required field not being honored

### ISSUE THREAD

**Issue by proimage** [percipioglobal/craft-colour-swatches#32]
Marking a color swatch field as required doesn't prevent an entry with no swatch selected from being saved...

Craft CMS 3.3.18
Colour Swatches 1.2.3

**Comment by JayBox325** [comment]
This seems to be a recurring issue that was fixed once, but it appears to be back.

**Comment by terryupton** [comment]
Any update on this as I have just come across this too and need to ensure clients choose a colour per page.

**Comment by WeArePercipio** [comment]
We have some time set aside this week to solve this issue, thanks for the bug report
