### ISSUE TITLE
Swatches displaying with checkerboard pattern in Control Panel

### ISSUE THREAD

**Issue by paulgoodfield** [percipioglobal/craft-colour-swatches#34]
After updating from plugin version 1.2.3 to 1.2.7, the swatches on the fields in the Control Panel are displaying a checkerboard pattern rather than as a solid colour.

<img width="272" alt="checkerboard-pattern-swatches" src="https://user-images.githubusercontent.com/1381838/75984027-95acbe00-5ee1-11ea-82bf-ea1ce87aed8d.png">

Craft Version: 3.3.19
Plugin Version: 1.2.7

Here is my `colour-swatches.php` config file:

```php
<?php
return [
	'colours' => [
		[
			'label'   => 'Coal Dark',
			'color'   => '#141A1E',
			'default' => true
		],
		[
			'label'   => 'Coal Light',
			'color'   => '#1D252D',
			'default' => false
		],
		[
			'label'   => 'Coal Grey',
			'color'   => '#5A5E61',
			'default' => false
		],
		[
			'label'   => 'Plum',
			'color'   => '#5A2D58',
			'default' => false
		],
		[
			'label'   => 'Wine',
			'color'   => '#A12242',
			'default' => false
		]
	]
];
```

**Comment by michtio** [comment]
@paulgoodfield This has been resolved in Version 1.3.0
