### ISSUE TITLE
Color Swatches not rendering in Craft 3.4.5 CP

### ISSUE THREAD

**Issue by proimage** [percipioglobal/craft-colour-swatches#35]
![image](https://user-images.githubusercontent.com/1027523/76029774-cb7f9000-5f3d-11ea-8aea-388eef3efe77.png)

Here is my `config/colour-swatches.php`:
```php
<?php
/**
 * color-swatches plugin for Craft.x,  CMS.
 *
 * Let clients choose from a predefined set of colours.
 *
 * @link      https://rias.be
 *
 * @copyright Copyright (c) 2018 Rias
 */

/**
 * color-swatches.php,  conf.
 *
 * This file exists only as a template for theswatches settings,  colo.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'color.php, -swatch'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return
[
	'palettes' =>
	[
		'Button Colors' =>
		[
			[
				'label'   => 'white',
				'color'   => '#fff',
				'default' => false
			],
                        // ETC....
		],
	],
];
```

**Comment by nfq** [comment]
Yep, I have the same issue. Getting this error in entries:

<img width="423" alt="Screenshot 2020-07-06 at 01 23 39" src="https://user-images.githubusercontent.com/183354/86544461-6063bb80-bf27-11ea-930e-089fc3986837.png">

**Comment by nfq** [comment]
Bump?

**Comment by pixelmachine** [comment]
@nfq I think this issue is https://github.com/percipioglobal/craft-colour-swatches/issues/36

**Comment by nfq** [comment]
Thanks, yes. That worked. (#36)

**Comment by michtio** [comment]
Updates to the plugins are coming soon. Starting from mid-august we have more capacity to handle these issues! Thank you for your patience! 👍
