### ISSUE TITLE
Migration Issue

### ISSUE THREAD

**Issue by keyurshah** [percipioglobal/craft-colour-swatches#36]
Thanks for taking over the plugin!

Unfortunately I upgraded and it seems that we've lost the data. Is there anyway to keep compatibility with previously created fields?

![image](https://user-images.githubusercontent.com/744385/83543939-04ce8a00-a4b2-11ea-9aa9-6e113f05fccb.png)

**Comment by michtio** [comment]
@keyurshah, we will look into this as soon as possible! It's currently a bit hectic with everything, but if you lock to `1.2.7` everything should be working as expected, since the last release only has some updated namespacing. So at least you could move on and keep on using it!

**Comment by medoingthings** [comment]
Same here. `1.2.8` broke the plugin for my installation. Luckily I noticed that before deploying to production. Going back to 1.2.7 fixed it for the moment.

Thanks for maintaining this plugin!

**Comment by keyurshah** [comment]
Thanks, I changed it to 1.2.7 and that worked.

**Comment by mattslack** [comment]
I had the same issue, running the following SQL fixed it for me, YMMV:

```sql
UPDATE fields SET type = REPLACE(type, 'rias\colourswatches\fields\ColourSwatches', 'percipioglobal\colourswatches\fields\ColourSwatches');
```

**Comment by aaronwaldon** [comment]
Got this working with an SQL snippet similar to @mattslack's:
```sql
UPDATE fields SET `type` = 'percipioglobal\\colourswatches\\fields\\ColourSwatches' WHERE `type` = 'rias\\colourswatches\\fields\\ColourSwatches'
```

**Comment by mtnorthrop** [comment]
This is an issue for me as well. Maybe it would help to make the old class names (including the namespace) aliases of the new names, and then create a migration that updates the `type` column in the database.

**Comment by michtio** [comment]
@mtnorthrop we will make some time this week to address the update issues! 
@aaronwaldon @mattslack feel free to PR.

**Comment by michtio** [comment]
Updates to the plugins are coming soon. Starting from mid-august we have more capacity to handle these issues! Thank you for your patience! 👍

**Comment by mildlygeeky** [comment]
For anyone else who is dead in the water right now after this, dropping this inside your site's `migrations` folder (or create a `migrations` folder if you don't have one) will get you up and running: https://gist.github.com/mildlygeeky/50d9d9b8e0a74fc5e343859c508a6e4b

**Comment by michtio** [comment]
@WeArePercipio could you update the plugin with the above gist? 

Thank you @mildlygeeky for the gist btw!

**Comment by WeArePercipio** [comment]
updated in version 1.4.0
