### ISSUE TITLE
Use custom properties in colours config

### ISSUE THREAD

**Issue by TomDeSmet** [percipioglobal/craft-colour-swatches#40]
I'm using the colour-swatches config with only custom colours (no palettes).
I'm using Tailwind CSS and I noticed that you can add custom properties to the palettes such as 'teal-500'.
Is it possible to use this inside the colours array too? Can't seem to get the data out when dumping `fieldName`.

**Comment by TomDeSmet** [comment]
I just used palettes, that works too.

**Comment by WeArePercipio** [comment]
Hey Tom, 

It will certainly be possible to do that in coming releases - however to get this out quick (as we needed the function for a project launching tomorrow) we wanted to minimise disruption to previous versions & installs. 

Feel free to add a feature request so it stays on our radar though... and yes in the interim, you can use the `color` array to output more useful values like classes, data-attributes and the likes

J
