### ISSUE TITLE
Selecting colorField to be shown in entries list gives 400 bad request error

### ISSUE THREAD

**Issue by bzin** [percipioglobal/craft-colour-swatches#42]
So I am trying to display the color the user select for a specific entry in the Entries list in the CP.

Steps to reproduce:
- Create a `colorField` and add it to an Entry
- Select the `colorField` to be displayed in the Entries list

Good to know that my `colorField` has its options defined in the `colour-swatches.php` config file.

_Error message displayed in debug toolbar:_
<img width="1654" alt="CleanShot 2020-08-06 at 09 28 27@2x" src="https://user-images.githubusercontent.com/382735/89509454-3f60e580-d7c7-11ea-9c58-6b8d23947949.png">

**Comment by WeArePercipio** [comment]
ah good spot @bzin - expect a bug fix later on today.
