### ISSUE TITLE
Twig template error when fieldValue is set to null

### ISSUE THREAD

**Issue by JordyHeemskerk** [percipioglobal/craft-colour-swatches#43]
The new code sets the value of `fieldValue` to `null` if it is undefined, which breaks the template.

The template tries to ensure `fieldValue` is defined before accessing it, but Twig treats `null` as defined. This lead to the following:
- `fieldValue is defined` -> `true`
- `fieldValue is not null` -> `false`

So the checks for `fieldValue` should probably be updated to `null` checks, instead of `defined` checks.

**Comment by architchandra** [comment]
My project's `composer.json` file still uses the old name `rias/craft-colour-swatches` and the fix for this error seems to have been pushed under `percipioglobal/craft-colour-swatches`. `composer update` is not able to see the version with the fix.

What can I do to get the fixes?
