### ISSUE TITLE
colour is being saved but goes back to "default colour" in cms

### ISSUE THREAD

**Issue by marina-moca** [percipioglobal/craft-colour-swatches#44]
Noticed this issue after upgrading to Craft 3.5.

The color is being saved:

![Screenshot at Aug 17 14-58-20](https://user-images.githubusercontent.com/56370392/90353390-2d6e2500-e09a-11ea-86fa-15c245773224.png)

But in the cms shows the default color:

![Screenshot at Aug 17 14-54-24](https://user-images.githubusercontent.com/56370392/90353418-424ab880-e09a-11ea-8500-ad0e14816c33.png)

**Comment by WeArePercipio** [comment]
Could you confirm your plugin version number please @marina-moca?

**Comment by meestaben** [comment]
@WeArePercipio I'm seeing the same issue, version 1.3.2.1

**Comment by marina-moca** [comment]
> Could you confirm your plugin version number please @marina-moca?

@WeArePercipio version 1.3.2.1
