### ISSUE TITLE
colour-swatches.php

### ISSUE THREAD

**Issue by MattWilcox** [percipioglobal/craft-colour-swatches#50]
Well, as a Brit this is the first time I've ever been caught out _in reverse_ for pre-emptively assuming the file name would be the American English version, and not the British.

Could I suggest aliasing both spellings?

**Comment by michtio** [comment]
Hah, thanks for the issue @MattWilcox we'll put it in our queue! 👍

**Comment by WeArePercipio** [comment]
updated in version 1.4.0
