### ISSUE TITLE
Inconsistent use of "colour" and "color"

### ISSUE THREAD

**Issue by JayBox325** [percipioglobal/craft-colour-swatches#53]
Further to #50 (I'm sure this will get tackled in fixing that), I'd like to raise the inconsistency of where the word is used. Personally, I'm a Brit, but I still would rather use the Americanism for consistency across my code.

But there are some instances where "Colour" and "Color" are used in the same place. See below:
![image](https://user-images.githubusercontent.com/13233809/94172005-da05a880-fe89-11ea-9f18-87b8189770b5.png)

If they could all be "color" that'd be lovely. 🙌🏻

**Comment by WeArePercipio** [comment]
addressed in version 1.4.0

**Comment by JayBox325** [comment]
Lovely, thanks for your work on this. It's been invaluable for some of my recent projects.
