### ISSUE TITLE
Updating class strings in the config file don't take effect immediately or even on just a resave of the entry.

### ISSUE THREAD

**Issue by terryupton** [percipioglobal/craft-colour-swatches#55]
I have found that if I need to update a class string in the config file, that this is no immediately available in the template/out-put. Instead, I have to manually force this to change. However, just resaving the entry doesn't seem to trigger this either. Instead I have to edit the entry and remove the colour, then save. I then have to edit then entry again and re-applying the colour -> saving again. 

I am not sure how this gets parsed and passed into the twig templates, but at the minimum, it would be super handy if just resaving the entries would trigger the classes to be updated. 

I can see this being a huge problem down the line if I need to update a classname or colour style. If I had to manually save each entry to trigger this.

Here is a shorted example of my 'palettes' array:
```
palettes' => [
    'Services' => [
      [
        'label'   => 'green',
        'default' => false,
        'color'   => [
          [
            'color'          => '#65942d',
            'classA'         => 'green',
            'classB'         => 'blue',
            'textClassA'     => 'text-green-500',
            'bgClassA'       => 'bg-green-500',
            'bordegClassA'   => 'border-green-500',
            'textClassB'     => 'text-blue-500',
            'bgClassB'       => 'bg-blue-500',
            'borderClassB'   => 'border-blue-600',
            'gradientFull'   => 'from-green-500 to-blue-600',
            'gradientClassA' => 'from-green-200 to-green-600',
            'bgBanner'       => 'bg-green-900',
            'arrow'          => 'text-blue-600',
            'barBanner'      => 'bg-green-300',
          ],
        ],
      ],
  ],
];
```

I hope the above is clear, but happy to try and explain better or produce a screencast if not.

**Comment by WeArePercipio** [comment]
That is some array there - didn't anticipate the custom config being used to this extent :) 

I have this update mostly in hand by fetching the config data again on entry save - I have a few more tests to run and a bit of time in the coming days to finish up on this, so expect version 1.4.2 to fix when released.

**Comment by onebrightlight** [comment]
Just ran into this myself where I had to add a new class so that Tailwind can use `JIT` compiling. I ended up resaving entries, but this would definitely get unwieldy on a project that has been in use for a while.

**Comment by onebrightlight** [comment]
Running into this issue again as it ate up 30 minutes of my day trying to figure out why this wasn’t updating until I remembered to check this issue. So anyway, hi, future me! I hope you remember the procedure outlined above!

**Comment by michtio** [comment]
@onebrightlight , the main issue is using a config file here. As that doesn't automatically is getting changed.

Working on a new colour-swatches version ( a "pro" version ) where these configs will be able to set / read in the field settings in the plugin itself

**Comment by onebrightlight** [comment]
Understandable! That said, perhaps a command in the CLI could allow us to update/change values?
