### ISSUE TITLE
"Getting unknown property" error in control panel since upgrade to 1.4.1

### ISSUE THREAD

**Issue by mtnorthrop** [percipioglobal/craft-colour-swatches#59]
When trying to view a Color Swatches field in the control panel, this error appears:
`Getting unknown property: percipioglobal\colourswatches\models\Settings::colours`

It appears that this error is being thrown from line 161 of `/src/fields/ColourSwatches.php`, and is due to the fact that the `$colours` property was removed from `/src/models/Settings.php` in version 1.4.1 of the plugin.

**Comment by mtnorthrop** [comment]
Thanks for that! If I could make a suggestion, though, it looks like that line might not have been a typo, but a fallback from `$plugin->settings->colors` to `$plugin->settings->colours`, if the first property was null. This is a bit clearer if we format the original code differently:
```php
'configOptions' => Plugin::$plugin->settings->colors 
    ? Plugin::$plugin->settings->colors 
    : Plugin::$plugin->settings->colours,
```

If the `colours` property no longer exists, we could probably drop the ternary altogether and just do:
```php
'configOptions' => Plugin::$plugin->settings->colors,
```

**Comment by michtio** [comment]
Thanks for the remarks @mtnorthrop we do have a major 2.0 release planned for this in 2021 with a lot more improvements and probably an entire codebase rewrite 🗡️

**Comment by WeArePercipio** [comment]
> Thanks for that! If I could make a suggestion, though...
> If the `colours` property no longer exists, we could probably drop the ternary altogether and just do:
> 
> ```
> 'configOptions' => Plugin::$plugin->settings->colors,
> ```

yeah there are several of these carryovers throughout that need to be addressed and cleaned - which will happen over the coming days. As @michtio says though, there's a full rebuild in the works with a bunch of new features including GraphQL and feedme support.
