### ISSUE TITLE
Swatches no longer in the admin and editable

### ISSUE THREAD

**Issue by JayBox325** [percipioglobal/craft-colour-swatches#65]
We have been using this plugin on a project for about three months and it's worked great, but we've recently updated our plugins and now we can no longer see our themes we've added in our config file and we can't even manually add them for now.

No console warnings either. See below:
![swatches-bug](https://user-images.githubusercontent.com/13233809/105696542-63da8680-5efb-11eb-87ee-e4ed9835a695.gif)

![image](https://user-images.githubusercontent.com/13233809/105696710-971d1580-5efb-11eb-9a64-45e8ba31c254.png)

Config is: (and hasn't changed since initial setup)
```
return [

    // Predefined colours
    'colours' => [
        [
            'label'   => 'White', 
            'color'   => '#FFFFFF',
            'default' => false,
        ],
        [
            'label'   => 'Gray', 
            'color'   => '#F8F9F4',
            'default' => true,
        ],
        [
            'label'   => 'Chartreuse', 
            'color'   => '#cfdc4a',
            'default' => false,
        ],
    ],
];
```

This was originally a required field, but as the user cannot select a theme, this was breaking all content blocks that used it (90% of them).

Versions:
CraftCMS: 3.5.17.1
Colour Swatches: 1.4.1.1

**Comment by WeArePercipio** [comment]
Thanks @JayBox325  - 

You will need to change your `colours` config over to `colors` - we should have made this a breaking change release jump, so apologies for that. That should kick things into place. 

That said, I have a few updates to make on this though so, I'll get an update pushed this week 👍

**Comment by JayBox325** [comment]
Ah noted. Thanks for the quick response. All updated.
