### ISSUE TITLE
Vizy Support

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [percipioglobal/craft-colour-swatches#66]
Hey All,

I'm test driving Vizy from Verbb and it looks like the Colour Swatch plugin is not saving the color selected inside of the Vizy field. On save the field selected just reverts to the first one in the list. I realize that Vizy is super new, but I thought I'd call that out here.

I'm on the latest version of Craft and your plugin. 

Thanks gang!

**Comment by DynamiteGoesBoom** [comment]
It may or may not be your plugin after all. I'm getting some other odd behavior with Vizy now too. So I'll close this issue until Vizy is more stable :) Sorry for the bother :)

**Comment by engram-design** [comment]
Quick note @DynamiteGoesBoom that https://github.com/percipioglobal/craft-colour-swatches/pull/68 should also fix another Vizy issue that's cropping up.
