### ISSUE TITLE
Unable to save colour selection if swatches have no "Labels"

### ISSUE THREAD

**Issue by adrianjean** [percipioglobal/craft-colour-swatches#69]
**Problem:**
If I configure some swatches, but don't assign any value to the "Label" for each (admittedly I was lazy and didn't want to have labels...), then in the entry form, make a swatch selection and save that entry, the selection isn't saved.

**Workaround/Solution:**
Adding labels for each colour allows the swatch field to behave normally.

ps. Thank you for an amazing plugin!

**Comment by cookie10codes** [comment]
Hi @adrianjean,

Thanks for getting in touch. Sorry it took a while for us to reply. There's no other way than adding the labels in the config file, these values we use to map out the selected colour from the palette or predefined colors.
