### ISSUE TITLE
Craft CMS update (3.7.20) prevents selection indicator being visible 

### ISSUE THREAD

**Issue by circa1983** [percipioglobal/craft-colour-swatches#73]
When a color swatch is selected on a field, the selected ring is not visible until the user clicks on something else and it looses focus.

This issue is caused by [Focus visible #10058](https://github.com/craftcms/cms/pull/10058/files#diff-9de912f41aa82e596057243e576dc259b4faeef35df220597134e41f503ef288R39) part of the [Craft CMS 3.7.20 - 2021-11-06](https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#3720---2021-11-06) release.

Possible fix would be to update [ColourSwatches.css (line 58)](https://github.com/percipioglobal/craft-colour-swatches/blob/2072124925445e55aa02d3acd2d1f075242706e5/src/assetbundles/colourswatchesfield/dist/css/ColourSwatches.css#L58)  from  `.color-swatches button.active {` to 

```
.reduce-focus-visibility .color-swatches button.active,
.color-swatches button.active {
 ```

**Comment by michtio** [comment]
Same as #72

**Comment by circa1983** [comment]
apologies! dont know how I didn't see that

**Comment by michtio** [comment]
correct @circa1983 , working on a quick fix for this that I'll push out shortly :)
