### ISSUE TITLE
Selection styling is gone

### ISSUE THREAD

**Issue by kevinmu17** [percipioglobal/craft-colour-swatches#77]
When choosing a color or opening an entry with the color plugin field, there is no "current" selected visible.

Version: 1.5.0.3

**Comment by kevinmu17** [comment]
I see that this problem crawled in with Version 1.4.2.1. After this all versions are broken with styling the active option

**Comment by WeArePercipio** [comment]
> When choosing a color or opening an entry with the color plugin field, there is no "current" selected visible.
> 
> Version: 1.5.0.3

Please open a new issue for this with any additional information

**Comment by WeArePercipio** [comment]
> I see that this problem crawled in with Version 1.4.2.1. After this all versions are broken with styling the active option

Please provide a screenshot and as much additional information as possible. Craft version, etc

This is a free plugin, so any additional information you provide saves us time in debugging and any resolution.

**Comment by kevinmu17** [comment]
A little time before closing an issue would be nice to... please reopen it because it is still an issue.

This orange ring is missing in version 1.5.0.3
<img width="63" alt="Screenshot 2022-01-12 at 16 52 39" src="https://user-images.githubusercontent.com/8747373/149174948-dbb602bb-adcf-4876-8dc0-415969bae25b.png">

It is now showing this:
<img width="47" alt="Screenshot 2022-01-12 at 16 58 19" src="https://user-images.githubusercontent.com/8747373/149175475-4945b324-89a5-49ec-91f8-cc8d0ff20933.png">

When opting an default in the settings it is not working either... it feels totally broken
