### ISSUE TITLE
Selected active state not showing active state colour after saving or page reload in admin panel

### ISSUE THREAD

**Issue by merwinpoulose** [percipioglobal/craft-colour-swatches#78]
![Screen Shot 2021-12-21 at 2 16 32 PM](https://user-images.githubusercontent.com/15919557/146854275-e1d87e1b-230c-4b9c-a66c-9f1874e352a2.png)

Currently  when I select and save a colour, after the page reload the active state is not showing the active colour.
Can you please help me with this?

Version:
    "percipioglobal/craft-colour-swatches": "1.5.0.3"
"craftcms/cms": "3.6.17",

**Comment by merwinpoulose** [comment]
button-active class is missing!

**Comment by merwinpoulose** [comment]
Fix:

/* Currently when you click on a colour button, it just add a class active, not button-active */
.color-swatches .button-active {
    box-shadow: 0 0 0 3px #F2842D;
}

.color-swatches pre {
    font-size: 0.75rem;
    font-family: courier;
}

/* small fix or you can update the button class to button-active */
.color-swatches .active {
    box-shadow: 0 0 0 3px #F2842D;
}

**Comment by michtio** [comment]
thank you @merwinpoulose we are back from our holiday break, will look into this shortly :)

**Comment by michtio** [comment]
This has been fixed in the 1.5.0.4 release ( hopefully for once and for all :D )
