### ISSUE TITLE
Randomly pick a set of colors from the color-swatches.php setup

### ISSUE THREAD

**Issue by romainpoirier** [percipioglobal/craft-colour-swatches#84]
I would like to randomly get a set of color from my `color-swatches.php` setup (I have currently only one set).
This can be useful in my case when the field is not filled, so one is randomly picked.

From a native Dropdown field, I could probably pick them using `craft.fields.getFieldbyHandle('handle').settings.options`.
How can I achieve this using the colour-swatches custom plugin?

**Comment by michtio** [comment]
Hey @romainpoirier 

Currently we don't have any possibilities to pick a random colour on save when nothing has been selected, but I do like the idea.
We'll tinker about this on how to best implement in the plugin. Thank you for the idea!

**Comment by michtio** [comment]
@romainpoirier we had some tinkering about this. 

Would it make sense to introduce an extra field setting ( lightswitch maybe ) when a field gets created, and when no value is selected it picks a random colour. Or would it make more sense to add an option to the actual colour palette where "random" can be selected?

**Comment by romainpoirier** [comment]
> Would it make sense to introduce an extra field setting ( lightswitch maybe ) when a field gets created, and when no value is selected it picks a random colour.

Yep, that could be that. Or a general setting.

> Or would it make more sense to add an option to the actual colour palette where "random" can be selected?


I think this makes more sense. And it would be useful to be able to be able to set the random setting by default or not.

**Comment by cookie10codes** [comment]
Hello @romainpoirier,

We've implemented the feature, there's now a settings switch on the field where you can select if a random color needs to be picked if the user doesn't.
