### ISSUE TITLE
[Craft 4]: Required colour swatch field can save without option being checked

### ISSUE THREAD

**Issue by Antimated** [percipioglobal/craft-colour-swatches#90]
Hey

I have 2 required colour swatch fields in side a matrix. Both fields are required but I can still save the entry even when I don't select a color option. The following fields still both save even if "Navigatie kleur" field is not selected. The color data is provided by a `colour-swatches.php` config file and had had other data in the past.

![Screenshot 2022-05-09 at 14 50 29](https://user-images.githubusercontent.com/2869409/167413401-5769168e-3f91-4b7b-8b4b-5ffd094989cb.png)

**Additional info**
- Craft version: 4.0.1
- Plugin version: 1.5.2

**Comment by michtio** [comment]
Thanks for the issue @Antimated

This has been resolved in 4.0.2 , just pushed that out!
