### ISSUE TITLE
[Craft 4] Field settings html fails to render

### ISSUE THREAD

**Issue by stereomyth** [percipioglobal/craft-colour-swatches#91]
Just installed the plugin on a brand new Craft 4 install. The field settings template will not load.
 
`Error: Class "percipiolondon\colourswatches\fields\Plugin" not found in .../vendor/percipioglobal/craft-colour-swatches/src/fields/ColourSwatches.php:213`

I guess it should be doing `ColorSwatches::$plugin` rather than `Plugin::$plugin`?

Additional info
- Craft version: 4.0.2
- Plugin version: 4.0.3

**Comment by cookie10codes** [comment]
thanks @stereomyth, we're going to investigate

**Comment by cookie10codes** [comment]
@stereomyth the issues has been resolved and there's a new release with this fix 👍🏼
