### ISSUE TITLE
Craft4 update: Unable to find component class 'percipioglobal\colourswatches\fields\ColourSwatches'.

### ISSUE THREAD

**Issue by Havnevik** [percipioglobal/craft-colour-swatches#92]
Field not found after craft4 update

Error shows up on 'settings/fields/edit' page
Unable to find component class 'percipioglobal\colourswatches\fields\ColourSwatches'.

The craft log also reports (but I guess that's unrelated): 
The message file for category 'colour-swatches' does not exist: 
[...]/vendor/percipioglobal/craft-colour-swatches/src/translations/nb/colour-swatches.php

"craftcms/cms": "^4.0.0"
"percipioglobal/craft-colour-swatches": "^4.0"

**Comment by michtio** [comment]
Hey @Havnevik 

Can you confirm that you have installed version `4.0.4` of colour-swatches, as I see you only use:

```
"percipioglobal/craft-colour-swatches": "^4.0"
```

This should be 

```
"percipioglobal/craft-colour-swatches": "^4.0.4"
```

**Comment by ZapaNOR** [comment]
Can confirm.
Currently on Craft CMS 4.0.3 with colour swatches 4.0.4 and getting the same error.

![Screenshot 2022-05-23 at 09 53 09](https://user-images.githubusercontent.com/53942798/169770847-7a937ef8-eddc-4ef8-a3c7-e31221204ff6.png)
![Screenshot 2022-05-23 at 09 53 16](https://user-images.githubusercontent.com/53942798/169770851-de3f8c88-65cb-4bdd-85a0-377ecb2e89eb.png)

**Comment by ZapaNOR** [comment]
Update:
Go to settings -> fields, find the colour swatches field, edit it and select field type "Colour swatches" from the dropdown.
Remember to configure the field type again. Save. Then it works.

**Comment by michtio** [comment]
Thanks for the update @Mathias-Syversen 

We will have a look today to the issue and push an update out once the bug has been resolved.

**Comment by cookie10codes** [comment]
hi @Havnevik,

Sorry to come back to you for this issue. But did you upgrade Craft 3 to Craft 4 for this project? 

Thanks for the additional information

**Comment by michtio** [comment]
@Mathias-Syversen I think I know the issue at hand tho.
Between Craft 3 > Craft 4 the namespace has changed. So it's not:

`percipioglobal/craft-colour-swatches` anymore but `percipiolondon/craft-colour-swatches`

On that hand we had an error in our migration as well! Update will go out shortly + adjusted warning in the Changelog :)

**Comment by Havnevik** [comment]
Sorry for the late respons. Yes I have "^4.0.4". @Mathias-Syversen suggestion worked for me as well. Thanks.

**Comment by kevinmu17** [comment]
```js
composer require percipiolondon/craft-colour-swatches
```

throws an error:
 Could not find a matching version of package percipiolondon/craft-colour-swatches. Check the package spelling, your version constraint and that the package is available   
  in a stability which matches your minimum-stability (stable).

**Comment by cookie10codes** [comment]
@kevinmu17 depends on which Craft version you're using
Craft 3: percipioglobal/craft-colour-swatches
Craft 4: percipiolondon/craft-colour-swatches
