### ISSUE TITLE
Custom attributes can only be set as a child of color property?

### ISSUE THREAD

**Issue by MattWilcox** [percipioglobal/craft-colour-swatches#94]
I'd like to be able to access custom attributes at the level of the label and not only the level of the colour.

```
<?php
return [
	// Custom  palettes, fixed options [label, default (boolean), colour (array(colour, customOptions)) ]
	'palettes' => [
		'Brand Compliant' => [  // custom label (required)
			[
				'label' => 'White', // custom label (required)
				'default' => true,  // default could be true/false (option is required)
				'customClass' => 'swatch1',
				'color' => [
					[
						'color' => '#ffffff', // the colour shown in the fieldtype (required)
						'otherCustomClass' => 'boop'
					],
					[
						'color' => '#2d5665' // the contrast colour for readable text
					]
				]
			], ...
```

`{{ fieldname.label }}` - outputs "White"

`{{ fieldname.color[0].color }}` outputs "#ffffff"

`{{ fieldname.customClass }}` - errors with `Calling unknown method: percipioglobal\colourswatches\models\ColourSwatches::customClass()`

`{{ fieldname.color[0].otherCustomClass }}` - outputs "boop"

Is this not possible?

**Comment by michtio** [comment]
@MattWilcox currently this isn't possible, as we don't allow for top-level classes. As it's a little bit against the purpose of everything. 

Usually you'd set class names on the colour level as in the example you have shown. I don't really see any use of top level classes? Feel free to share an example in where it does makes sense. 

If you want to parse a colour, say a background or text colour from your palette you'd simple leverage the background class and the text class. If you only want a single class there is no stopping you from using that configured class in one of the colours to act as "main" class without ever touching the others. 

The reason that you have an array to add multiple colours is for displaying it in the CP and to be able to use utility classes, but if you simply have a single class you could use `fieldname.color[0].customClass` on the wrapping container.

**Comment by MattWilcox** [comment]
Yeah, it's because we want to output on the front end just a class for the "colour" which is in fact two colours (a main and a contrast). We're not outputting the colours in the mark-up there, we only need a class. We're outputting the colours as CSS Custom Properties elsewhere.

It just seems weird to attach a properly to a colour when the property belongs with the label, not the colour.

No worries, will fudge something else, cheers.

**Comment by michtio** [comment]
@MattWilcox it makes most sense to add the colour properties on colour level. You could simply use your class on the first level of the array and only output that.

If in your case as you say you have a contrast + a main, you could simply do something like ( just with a TW example here ):



```
<div class="{{- field.color[0].class -}}">
  <p class="{{- field.color[1].class -}}"> </p>
</div>
```

```
Brand Compliant' => [  // custom label (required)
			[
				'label' => 'Red', // custom label (required)
				'default' => true,  // default could be true/false (option is required)
				'color' => [
					[
						'color' => '#ff0000', // the colour shown in the fieldtype (required)
						'class' => 'bg-red-500',
					],
					[
						'color' => '#ffffff', // the contrast colour for readable text
                                                  'class' => 'text-white',
					]
				]
			],
```

As in the above you'd have something that shows red/white to your authors, where red would be the background of let's say a CTA block, and all the text would be white.

That's in general how colour-swatches gets used the most. In it's lifespan you are the first person to ask for a class addition on top level.

In your particular use case it might make sense.
I will leave this issue open, we are currently working on improving the UI in the CP of our plugin, and might push this along with it as an update.

I think we're ± 2 weeks away from releasing the new version.

**Comment by MattWilcox** [comment]
Cheers.

Yeah, it's because we're setting two linked colours in one step - but they're kinda semantically linked because the point is that the text colour is pre-defined to always have sufficient contrast with the background colour. But... kinda pointless to explicitly set both in mark-up. That said, it's not exactly terrible to have to do that either - just a bit redundant.

**Comment by cookie10codes** [comment]
hi @MattWilcox, we released a new version for Craft 3 and Craft 4 with this feature
