### ISSUE TITLE
Colors not saving when in Matrix inside of Super Table

### ISSUE THREAD

**Issue by allenpieper** [percipioglobal/craft-colour-swatches#98]
Hi, great plugin and thanks for developing it!

Currently I'm experiencing a problem where a color selection won't save when the Color field is in a Matrix block. It's saving in my Neo blocks and as a direct child of an entry. But when I nest it inside a matrix and select a color, it's not saving my color selection.

I looked at other, older issues about the 'active' state not showing up in the UI. This isn't that. I'm not actually getting any color output from twig.

EDIT:
This might actually be a SuperTable issue. My matrix field is inside of a SuperTable. 

Craft 4.1.0.2
Colour Swatches 4.1.0

**Comment by michtio** [comment]
Hey @allenpieper do you maybe have any more details about your setup, as I can't manage to replicate the issue. I tried adding a matrix into a supertable, and got output as expected:

<img width="251" alt="Screenshot 2022-07-08 at 12 58 02" src="https://user-images.githubusercontent.com/5818021/177979514-5200b4e0-ecd9-431b-9c9b-6cb4dfd1771c.png">

With the following snippet:

```
{% for row in entry.supertable.all() %}
            <strong>Inside the supertable</strong><br />
            {%  for block in row.matrix.all() %}
                <strong>Inside the matrix</strong><br />
                {{  block.colour.label }}<br />
                {{  block.colour.color[0].color }}<br />
                {{  block.colour.color[0].background }}<br />
            {% endfor %}
        {% endfor %}
```
