### ISSUE TITLE
Multi-site support

### ISSUE THREAD

**Issue by benhaldenby** [percipioglobal/craft-colour-swatches#99]
Does the Colour Swatches plugin natively support Craft multi-site setups?

I support a landing project platform, built using Craft multi-site, where each client landing page is setup as a separate site, sharing a set of Content layout blocks using a Matrix field. On the front-end, each client shares the templates, but each have their own directory in /assets/ for CSS.

I'd like to add the Colour Swatches plugin to each layout block, to provide brand colour options, background-color, text color etc.

But it seems that the colour-swatches.php is inherently tied to the Craft installation, rather than an individual site.
Is there a way to specify colours for these individual sites? 

Thanks in advance,
Ben

**Comment by pixelmachine** [comment]
I was attempting to do something like this by doing the following in the config file. It works and shows the correct palettes but it seems to have trouble saving or something:

```php
$sitePalettes = [
  'siteOneHandle' => [ ... siteOnePaletteData ... ],
  'siteTwoHandle' => [ ... siteTwoPaletteData ... ]
]
return [
  'palettes' => [
    'Colours' => $sitePalettes[Craft::$app->request->getQueryParam('site')],
  ],
];
```

**Comment by pixelmachine** [comment]
Actually I just figured it out I think.

You need to make a generic palette with ALL the options, then per site.

```php
$useSite = Craft::$app->request->getQueryParam('site') ?? 'allSites';

$sitePalettes = [
  'allSites' => [ ... siteOnePaletteData & siteTwoPaletteData ... ]
  'siteOneHandle' => [ ... siteOnePaletteData ... ],
  'siteTwoHandle' => [ ... siteTwoPaletteData ... ]
]
return [
  'palettes' => [
    'Colours' => $sitePalettes[$useSite],
  ],
];

**Comment by cookie10codes** [comment]
hello @pixelmachine,

Apologies for taking so long to reply. The way around would be settings a global field. Select the pallet you want for that site.
